version: '3.6'
services:
  minio:
    image: minio/minio:RELEASE.2020-09-08T23-05-18Z
    volumes:
      - data1-1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio1
      MINIO_SECRET_KEY: minio1@123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    hostname: k8-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  storage-adapter:
    image: storage:1.0
    build:
      context: .
      dockerfile: storage/Dockerfile
    env_file:
      - storage/.env
    ports:
      - 50052:50052
      - 5005:5002

  glasswall-crawler:
    image: glasswallcrawler:1.0
    build:
      context: .
      dockerfile: gw_crawler/Dockerfile
    env_file:
      - gw_crawler/.env
    ports:
      - 5002:5000
    depends_on:
      - minio
      - rabbitmq

  rabbitmq-process:
    image: rabbit-mq:1.0
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    env_file:
      - rabbitmq/.env
    ports:
      - 50057:50057
      - 5006:5006
    restart: on-failure
    depends_on:
      - rabbitmq
      - minio
    links:
      - rabbitmq

  k8-file-distribution:
    image: k8-file-distribution
    build:
      context: .
      dockerfile: file_distribution/Dockerfile
    env_file:
      - file_distribution/.env
    ports:
      - 50051:50051
      - 5001:5001
    depends_on:
      - minio

  k8-file-processor:
    image: k8-file-processor
    build:
      context: .
      dockerfile: file_processor/Dockerfile
    env_file:
      - file_processor/.env
    ports:
      - 5000:5000
    links:
      - minio
      - rabbitmq
    depends_on:
      - rabbitmq

  glasswall-rebuild:
    image: glasswall-rebuild
    environment:
      PYTHONUNBUFFERED: 0
    build:
      context: .
      dockerfile: glasswall_rebuild/Dockerfile
    ports:
      - 5003:5003

  k8-s3-sync:
    image: k8-s3-sync
    env_file:
      - s3_sync/.env
    build:
      context: .
      dockerfile: s3-sync/Dockerfile
    ports:
      - 5004:5004
    links:
      - minio
    depends_on:
      - minio

volumes:
  data1-1: 
  